### ISSUE TITLE
Number of hits per route

### ISSUE THREAD

**Issue by lasseeee** [julienbourdeau/route-usage#16]
Tracking the number of times a route has been visited would be neat.

**Comment by julienbourdeau** [comment]
I added this at the beginning but without the time reference, I found that it wasn't so useful without time reference.

You might  get a route hit only 12 times, but the last call is yesterday and one route that was hit a 1000 times but hasnt been called for 2 years. So it gives the wrong sense of importance here I think.

Something per month would be great for instance, but then we start going into analytics 😄

**Comment by julienbourdeau** [comment]
I don't think I'll add this, it's getting to close to analytics for now.

Thanks for taking the time to share this.
