### ISSUE TITLE
Ignoring Telescope and Clockwork

### ISSUE THREAD

**Issue by fgilio** [julienbourdeau/route-usage#17]
Hi 👋!
Nice package, it's exactly what I was looking for and also for the same reason you explain in the readme 😅

I'm thinking that I could be useful to also ignore all [Telescope](https://github.com/laravel/telescope) and [Clockwork](https://github.com/itsgoingd/clockwork) routes, that would be `/telescope` and `__clockwork`. What do you think?

**Comment by julienbourdeau** [comment]
Definitely! We should ignore all package routes like those 👍
