### ISSUE TITLE
Detect non-existent controllers

### ISSUE THREAD

**Issue by szepeviktor** [julienbourdeau/route-usage#21]
Hello 👋 
Some routes may _loose_ their controllers.
This is my 3rd try on the matter.
https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/laravel/Commands/RouteCheckCommand.php

What do you think?

**Comment by julienbourdeau** [comment]
Can you explain how route lose their controller?

**Comment by szepeviktor** [comment]
You delete it :)

**Comment by julienbourdeau** [comment]
I see 😄 

I assume then you get a 404 so usage shouldn't be logged by the package. What error did you get?

**Comment by szepeviktor** [comment]
I'm not using your package.
This issue is an idea. 🗯️

**Comment by szepeviktor** [comment]
> I assume then you get a 404

I think it is rather a Fatal Exception.

**Comment by julienbourdeau** [comment]
Generally, I'd recommend declaring routes with the array notation so your editor will tell you there is a missing controller.

```php
Route::get('/yolo', [App\Http\Controllers\LifeController::class, 'yolo'])`
```

I think it will be out of scope of this project. Thanks for contribution and answering a year later 😅

**Comment by szepeviktor** [comment]
> so your editor will tell you

I run web applications and developers deploy weird things.
So I had to develop the above tool to check (in CI) that all controllers do exist.
