### ISSUE TITLE
Support multiple databases

### ISSUE THREAD

**Issue by ingalless** [julienbourdeau/route-usage#4]
Hi, great package idea!

I noticed the package appears to only support mysql.
The code is in `LogRouteUsage.php`
```php
DB::statement(
    "INSERT INTO route_usage
            (`identifier`, `method`, `path`, `status_code`, `action`, `created_at`, `updated_at`)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE `updated_at` = '{$date}'",
    [$identifier, $method, $path, $status_code, $action, $date, $date]
);
```

I think it would be possible to support multiple databases with a change in LogRouteUsage.php

I'll submit a pull request once I've got the tests passing 👍

**Comment by faizananwerali** [comment]
+1

**Comment by kasperhartwich** [comment]
+1

**Comment by oaloria** [comment]
+1

**Comment by julienbourdeau** [comment]
Hi 👋 

I have release 0.4 with support for other databases: https://github.com/julienbourdeau/route-usage/releases/tag/0.4

Thanks for your help and inputs!
