### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by rjsworking** [julienbourdeau/route-usage#9]
Hi I think you need to tag a new release.
I'm getting the old code when iI install the package.

I was looking to the code that have been installed and it's different from the github code updated 16 hours ago.

Cheers

**Comment by julienbourdeau** [comment]
Hi @rjsworking, 
Thanks for your interest!

I just tagged 0.2, you can find the changelog here: https://github.com/julienbourdeau/route-usage/blob/master/CHANGELOG.md

**Comment by rjsworking** [comment]
@julienbourdeau Thank you very much.
